# Generated by Django 5.2.7 on 2025-10-03 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_total', models.PositiveIntegerField(default=100)),
                ('seats_available', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='airlines.company')),
            ],
            options={
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_at'], name='airlines_fl_origin_9158a7_idx')],
                'unique_together': {('company', 'flight_no', 'departure_at')},
            },
        ),
    ]
